### PR TITLE
Add products test

### PR DESCRIPTION
**Pull request by c6liu**

### CODE REVIEW

**Review by LW256 — COMMENTED** [review]
It looks like there will be a merge conflict when merging. Can you fetch updates from the main branch?

**Comment by c6liu** [comment]
> It looks like there will be a merge conflict when merging. Can you fetch updates from the main branch?

I am using the latest main branch

**Comment by LW256** [comment]
Thank you for clarifying. I just noticed that the name of your newly added file differs from the existing one. So there will be no merge conflict.

**Comment by kckevinchenzkk** [comment]
I combined two test files for product into one. And I add a fixture to remove all the images that the test will create.

**Review by kckevinchenzkk — APPROVED** [review]

**Review by LW256 — APPROVED** [review]

**Pull request merged**
